"""Captions from the voiceover word timings (audio/vo/timing.json, written by build_vo.py).

Writes
  assets/captions.js      window.CAPTIONS for the burned-in caption layer
  renders/<name>.srt      sidecar captions for platforms that take a caption file
  renders/<name>.vtt

Chunking comes from audio/vo/script.json, per line:
  chunks   words per caption chunk, e.g. [5, 4] for "Your browser app needs data | from an outside API."
           (default: the whole line is one chunk). Break after punctuation; never split an article or an
           adjective from its noun.
  burn     false keeps the line out of the picture (the end card already writes it in sync) but in the sidecars

Every chunk is checked against the Netflix English timed-text rules (at most 42 characters per line, at most 20
characters per second, 5/6 s to 7 s on screen, gaps of 2 frames or at least 0.5 s) and the build fails when one
breaks. Fix it by merging chunks or by widening the line's gap_after, not by cutting words.

  python3 scripts/build_captions.py [name]      # name defaults to the project directory name
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NAME = sys.argv[1] if len(sys.argv) > 1 else ROOT.name
LEAD, TAIL = 0.08, 0.3          # a chunk appears just before its first word and lingers after its last
FRAME = 1 / 30
MAX_CHARS, MAX_CPS, MIN_DUR, MAX_DUR, MIN_GAP = 42, 20.0, 5 / 6, 7.0, 0.5


def build():
    lines = json.loads((ROOT / 'audio' / 'vo' / 'timing.json').read_text())
    script = {l['id']: l for l in json.loads((ROOT / 'audio' / 'vo' / 'script.json').read_text())['lines']}
    chunks = []
    for line in lines:
        words = line['words']
        sizes = script[line['id']].get('chunks', [len(words)])
        assert sum(sizes) == len(words), (line['id'], sizes, len(words))
        i = 0
        for n in sizes:
            ws = words[i:i + n]
            i += n
            chunks.append({'line': line['id'], 'burn': script[line['id']].get('burn', True),
                           'start': round(ws[0]['s'] - LEAD, 3), 'end': round(ws[-1]['e'] + TAIL, 3),
                           'words': [{'w': w['w'], 's': round(w['s'], 3)} for w in ws]})
    # a short chunk followed straight by the next one: delay the next in-time (it may sit on its first word,
    # within the 1-2 frames of speech that Netflix allows)
    for a, b in zip(chunks, chunks[1:]):
        if b['start'] - 2 * FRAME - a['start'] < MIN_DUR:
            b['start'] = round(min(b['words'][0]['s'], a['start'] + MIN_DUR + 2 * FRAME), 3)
    # hold a short chunk up to the minimum duration when the next one leaves room
    for a, b in zip(chunks, chunks[1:]):
        if a['end'] - a['start'] < MIN_DUR:
            a['end'] = round(min(a['start'] + MIN_DUR, b['start'] - 2 * FRAME), 3)
    # gaps are either 2 frames (chained) or at least half a second
    for a, b in zip(chunks, chunks[1:]):
        if b['start'] - a['end'] < MIN_GAP:
            a['end'] = round(b['start'] - 2 * FRAME, 3)
    for c in chunks:
        c['text'] = ' '.join(w['w'] for w in c['words'])
    return chunks


def check(chunks):
    problems = []
    for c in chunks:
        dur = c['end'] - c['start']
        cps = len(c['text']) / dur
        if len(c['text']) > MAX_CHARS: problems.append(f"{c['text']!r}: {len(c['text'])} chars > {MAX_CHARS}")
        if cps > MAX_CPS: problems.append(f"{c['text']!r}: {cps:.1f} cps > {MAX_CPS}")
        if dur < MIN_DUR - 1e-3: problems.append(f"{c['text']!r}: {dur:.2f} s < {MIN_DUR:.2f} s")
        if dur > MAX_DUR: problems.append(f"{c['text']!r}: {dur:.2f} s > {MAX_DUR} s")
    for a, b in zip(chunks, chunks[1:]):
        gap = b['start'] - a['end']
        if gap < 2 * FRAME - 1e-3 or (2 * FRAME + 1e-3 < gap < MIN_GAP - 1e-3):
            problems.append(f"gap {gap:.3f} s before {b['text']!r}")
    return problems


def stamp(t, sep):
    ms = int(round(t * 1000))
    h, ms = divmod(ms, 3600000)
    m, ms = divmod(ms, 60000)
    s, ms = divmod(ms, 1000)
    return f'{h:02d}:{m:02d}:{s:02d}{sep}{ms:03d}'


def main():
    chunks = build()
    for c in chunks:
        dur = c['end'] - c['start']
        print(f"{c['start']:6.2f}–{c['end']:6.2f} {'burn' if c['burn'] else 'file'} {len(c['text']):2d}ch {len(c['text']) / dur:4.1f}cps  {c['text']}")
    problems = check(chunks)
    if problems:
        raise SystemExit('caption rules broken:\n  ' + '\n  '.join(problems))
    js = '// generated by scripts/build_captions.py from audio/vo/timing.json\nwindow.CAPTIONS = [\n' + ',\n'.join(
        '  ' + json.dumps({k: c[k] for k in ('start', 'end', 'burn', 'words')}) for c in chunks) + '\n];\n'
    (ROOT / 'assets' / 'captions.js').write_text(js)
    out = ROOT / 'renders'
    out.mkdir(exist_ok=True)
    srt = '\n'.join(f"{i}\n{stamp(c['start'], ',')} --> {stamp(c['end'], ',')}\n{c['text']}\n" for i, c in enumerate(chunks, 1))
    vtt = 'WEBVTT\n\n' + '\n'.join(f"{stamp(c['start'], '.')} --> {stamp(c['end'], '.')}\n{c['text']}\n" for c in chunks)
    (out / f'{NAME}.srt').write_text(srt)
    (out / f'{NAME}.vtt').write_text(vtt)
    print(f'ok: {len(chunks)} chunks within the caption rules → assets/captions.js, renders/{NAME}.srt, renders/{NAME}.vtt')


if __name__ == '__main__':
    main()
