#!/usr/bin/env bash
# Start a video project from the skill's template: composition, helper scripts, vendored GSAP and a font.
#   bash <skill>/scripts/new-project.sh <project-dir>
# Then run the template once (see the skill's "Build loop") before replacing its content.
set -euo pipefail
DEST=${1:?project directory}
SKILL=$(cd "$(dirname "$0")/.." && pwd)
GSAP_VERSION=3.14.2
INTER_VERSION=5.2.8

if [ -e "$DEST/index.html" ]; then echo "$DEST/index.html exists; not overwriting" >&2; exit 1; fi
mkdir -p "$DEST/scripts" "$DEST/assets/js" "$DEST/assets/vendor" "$DEST/assets/fonts" "$DEST/audio/vo" "$DEST/renders"
cp "$SKILL/assets/index.html" "$DEST/index.html"
cp "$SKILL/assets/scene.js" "$DEST/assets/js/scene.js"
cp "$SKILL/assets/script.json" "$DEST/audio/vo/script.json"
for f in "$SKILL"/scripts/*; do
  [ "$(basename "$f")" = "new-project.sh" ] || cp "$f" "$DEST/scripts/"
done
# stubs until build_vo.py and build_captions.py overwrite them
printf '%s\n' '// generated by scripts/build_vo.py; empty until the project has a voiceover' 'window.VO = [];' 'window.VO_TOTAL = null;' > "$DEST/assets/timing.js"
printf '%s\n' '// generated by scripts/build_captions.py; empty until the project has a voiceover' 'window.CAPTIONS = [];' > "$DEST/assets/captions.js"

curl -fsSL -o "$DEST/assets/vendor/gsap.min.js" "https://cdn.jsdelivr.net/npm/gsap@$GSAP_VERSION/dist/gsap.min.js"
curl -fsSL -o "$DEST/assets/fonts/inter-latin-wght-normal.woff2" "https://cdn.jsdelivr.net/npm/@fontsource-variable/inter@$INTER_VERSION/files/inter-latin-wght-normal.woff2"
curl -fsSL -o "$DEST/assets/fonts/LICENSE-Inter.txt" "https://cdn.jsdelivr.net/npm/@fontsource-variable/inter@$INTER_VERSION/LICENSE"

# keep keys, renders and raw captures out of git
[ -e "$DEST/.gitignore" ] || cat > "$DEST/.gitignore" <<'EOF'
.env*
renders/
capture/raw/
snapshots/
audio/sfx-preview/
EOF
echo "project ready in $DEST (GSAP $GSAP_VERSION, Inter $INTER_VERSION)"
